apiVersion: v1
kind: Service
metadata:
  labels:
    app: admin-deployment
  name: admin-service
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /
spec:
  ports:
  - port: 32000
    protocol: TCP
    targetPort: 3000
  selector:
    app: admin-deployment
  type: NodePort
status:
  loadBalancer: {}
